databases:
  - name: mysitedb
    plan: free
    databaseName: ontherecord
    user: postgres

services:
  - type: web
    plan: free
    name: ontherecord
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ontherecordshop.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ontherecord
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4