# Generated by Django 5.0.1 on 2024-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=250)),
                ('artist', models.CharField(default='Unknown', max_length=100)),
                ('release_date', models.DateField(default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album_cover', models.URLField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('genre', models.ManyToManyField(to='main_app.genre')),
            ],
        ),
    ]
